/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.rdfdsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class RdfDslProposalProvider extends AbstractRdfDslProposalProvider {
}
