/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.rdfdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RdfDslStandaloneSetup extends RdfDslStandaloneSetupGenerated {

	def static void doSetup() {
		new RdfDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
